### ISSUE TITLE
JS-CSS problem

### ISSUE THREAD

**Issue by musicman3** [nkappler/ctxmenu#16]
Hello. Our layout designer still faces a css from js problem. This css has the highest priority. Therefore, we have to adjust the js file. In js, we've temporarily cleared the styles like this:

```
".ctxmenu": {},
".ctxmenu li": {}
```

etc.

Therefore, you need to somehow solve this problem. It's probably best to clear everything like we did. The js file is located at the bottom of the page and therefore there is no other css after it. This leads to the highest priority js-css 

It seems to me you can add a setting to the initialization to use inline css. And by default use css in a separate file.

**Comment by nkappler** [comment]
could you go in more detail which css rules are problematic and why you need to overwrite the source js file?

You should be able to just overwrite the defaults by adding your own css instead of changing the source css.

For example, the below snippet resets all rules either by using none, inherit or initial.
Of course you can also specify any other value you need.

```css

 .ctxmenu {
  border: none;
  padding: none;
  box-shadow: none;
  background: inherit;
  margin: initial;
  font-size: inherit;
  font-family: initial;
  z-index: initial;
},
.ctxmenu li: {
  margin: none;
  display: inherit;
  position: none;
},
```
